name: Tests

on:
  - push
  - pull_request

jobs:
  unit_tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2-beta

      - name: Restore
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Bootstrap
        run: npx lerna bootstrap

      - name: Build Specs
        run: npm run build:specs

      - name: Test App
        run: yarn run test:coverage

      - name: Upload Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
